name: publish npm package

on:
  push:
    branches: ["main"]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: "@jh-webworks"
      - run: echo registry=https://npm.pkg.github.com/jh-webworks >> .npmrc
      - run: echo ${{secrets.PUBLISH_GITHUB_TOKEN}} >> .npmrc
      # - run: npm install
      - name: push
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.PUBLISH_GITHUB_TOKEN}}
